---
## CI/CO para desplegar el .war de la plataforma
before_script:
  - echo "${CI_COMMIT_REF_NAME}"

stages:
  - deploy
  - war
  - reset
  - optional
deploy:
  stage: deploy
  script:
   -  echo "${CI_COMMIT_REF_NAME}"
   -  sh /usr/local/tomcat8/bin/shutdown.sh
   -  rm -rf /root/worldprofe
   -  rm -rf /usr/local/tomcat8/webapps/plataformawp/ROOT/*
   -  sudo git clone git@gitlab.com:frankjosue.vigilvega/worldprofe.git /root/worldprofe
  tags:
   - plataformawp
  when: always     
  only: 
    - master   

deploy_war:
  stage: war
  script:
   -  echo "${CI_COMMIT_REF_NAME}"     
   -  cp -r /root/worldprofe/war/* /usr/local/tomcat8/webapps/plataformawp/ROOT/
  tags:
   - plataformawp
  when: always
  only:
    - master

#deploy_optional:
#  stage: optional
#  script:
#   -  rm -rf /usr/local/tomcat8/webapps/plataformawp/ROOT/WEB-INF/classes/config/* 
#   -  cp -r /usr/local/tomcat8/webapps/plataformawp2/ROOT/WEB-INF/classes/config/* /usr/local/tomcat8/webapps/plataformawp/ROOT/WEB-INF/classes/config/
#  tags:
#   - plataformawp
#  when: always
#  only:
#    - master


deploy_reset:
  stage: reset
  script:
   -  chmod -R 777 /usr/local/tomcat8/webapps/plataformawp/
   -  sh /usr/local/tomcat8/bin/startup.sh
  tags:
   - plataformawp
  when: always
  only:
    - master